### ISSUE TITLE
Fix rsync error: permission denied

### ISSUE THREAD

**Issue by tunglinn** [ParkingReformNetwork/parking-lot-map#149]
![image](https://github.com/ParkingReformNetwork/parking-lot-map/assets/86996158/b4e3aea6-dbbb-4050-b70c-3bb1dd62890a)

A quick solution is to have Tony remove the files. However, we should also figure out why the workflow doesn't have delete permission.
- [ ] Add `--no-times` option
- [ ] Delete `icons/share-url-button.png`, `data/parking-lots.geojson`, and `data/cities-polygons.geojson` (and icons and data folder)
- [ ] Allow `PRN_SERVER_PRIVATE_KEY` to have delete privileges?

**Comment by Eric-Arellano** [comment]
> However, we should also figure out why the workflow doesn't have delete permission.

I believe it's because we can't delete the subfolders. But we can delete files in the immediate folder. We probably didn't set permissions recursively. That's usually fine since with Parcel we don't deploy any subfolders anymore.

**Comment by Eric-Arellano** [comment]
Fixed. We got our first green run :) 

<img width="853" alt="Captura de pantalla 2024-01-11 a la(s) 7 52 52 a m" src="https://github.com/ParkingReformNetwork/parking-lot-map/assets/14852634/f8555bc1-6725-4cbc-ae2d-39404e7a94e1">
