### ISSUE TITLE
Typing in the dropdown breaks the city info card on iPhone

### ISSUE THREAD

**Issue by JamesLowenthal** [ParkingReformNetwork/parking-lot-map#177]
To reproduce:

1) Load https://parkingreform.org/parking-lot-map on mobile.

2) Type any city name in the dropdown and select it

3) Note broken layout, see attached screenshot ![image](https://github.com/ParkingReformNetwork/parking-lot-map/assets/101603561/6cf37513-175f-4541-ac84-ae35975f01e7)

**Comment by JamesLowenthal** [comment]
Tricky to reproduce in devtools, might need to run an ngrok tunnel to my phone

**Comment by Eric-Arellano** [comment]
Fixed by https://github.com/ParkingReformNetwork/parking-lot-map/pull/181
