### ISSUE TITLE
Lazily load parking lot data only when the city is used

### ISSUE THREAD

**Issue by Eric-Arellano** [ParkingReformNetwork/parking-lot-map#88]
As of https://github.com/ParkingReformNetwork/parking-lot-map/pull/109, the parking lots JSON file is now 3.3 MB when built with Parcel. That's pretty big for users with slow Internet and mobile.

We can improve this by instead only loading the data for each city when it's relevant. We'll use something like Parcel's glob mechanism (https://parceljs.org/features/dependency-resolution/#glob-specifiers) and JavaScript's dynamic `await import`s to only load the city when it's in view.

There are two cases for that:

1. The city is explicitly selected via the URL or city toggle, which calls this function:

https://github.com/ParkingReformNetwork/parking-lot-map/blob/5eac44dcedf54076283597a701236124aaa7d521/src/js/setUpSite.js#L180

2. The user drags the map to a new city. The mechanism to detect this closely relates to https://github.com/ParkingReformNetwork/parking-lot-map/issues/112.

**Comment by tunglinn** [comment]
Create feature branch:
First PR:
- write script to split geojson
- get map to load new split geojson
- update scripts and tests

Second PR:
- implement lazy loading

**Comment by tunglinn** [comment]
Implemented via #142
